#CASE 1

a = 1
b = 2

soma = a+b 
print(soma)

#NO ASSEMBLY -> ORDEM DIRETA AO PREOCESSOR, SE QUISÉSSEMOS 1_2 ACC = 1, VALOR 2 IA PARA O ACUMULADOR 2, AÍ O CODIGO DA SOMA SERIA ATT, O RESULTADO DA SOMA IA PARA UM ACUMULADOR 3
